insert into dbModels_leafassessment (leaf_name, assessment_id_id, max_mark, published) values ("Compiles",1,5,1);
insert into dbModels_leafassessment (leaf_name, assessment_id_id, max_mark, published) values ("Executes",1,5,1);
insert into dbModels_leafassessment (leaf_name, assessment_id_id, max_mark, published) values ("Correct",1,10,0);
insert into dbModels_leafassessment (leaf_name, assessment_id_id, max_mark, published) values ("Exists",2,25,0);
insert into dbModels_leafassessment (leaf_name, assessment_id_id, max_mark, published) values ("Adheres",3,7,0);
insert into dbModels_leafassessment (leaf_name, assessment_id_id, max_mark, published) values ("Complies",3,3,0);
insert into dbModels_leafassessment (leaf_name, assessment_id_id, max_mark, published) values ("Working",4,5,1);
insert into dbModels_leafassessment (leaf_name, assessment_id_id, max_mark, published) values ("Waiting",4,10,0);
insert into dbModels_leafassessment (leaf_name, assessment_id_id, max_mark, published) values ("Compiles",5,5,0);
insert into dbModels_leafassessment (leaf_name, assessment_id_id, max_mark, published) values ("Does things",6,12,1);
insert into dbModels_leafassessment (leaf_name, assessment_id_id, max_mark, published) values ("Speaks",7,20,1);
insert into dbModels_leafassessment (leaf_name, assessment_id_id, max_mark, published) values ("Compiles",8,12,0);
insert into dbModels_leafassessment (leaf_name, assessment_id_id, max_mark, published) values ("Executes",9,5,0);